# Generated by Django 2.2.6 on 2019-10-24 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='wall',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='walls.Wall'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wall',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
