# Generated by Django 2.2.6 on 2019-10-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='int_indicator',
            field=models.SmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], default=-1),
        ),
    ]
