# Generated by Django 2.2.6 on 2019-10-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('walls', '0003_auto_20191024_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallmembership',
            name='roles',
        ),
        migrations.AddField(
            model_name='wallmembership',
            name='roles',
            field=models.ManyToManyField(to='core.UserRole'),
        ),
    ]
